### ISSUE TITLE
not working in 1.9 or incompatible with another plugin

### ISSUE THREAD

**Issue by matalaa** [colinmollenhour/Cm_OrderProducts#1]
Hi,

I've copied the files in app/code/community under Cm_OrderProducts-master but I'm not getting the columns added in the order grid

other extensions that I have:
- Raveinfosys_Deleteorder
- enhanced-admin-grids-editor
- TheExtensionLab/StatusColors

**Comment by colinmollenhour** [comment]
These kinds of conflicts are going to happen when you have a lot of Magento extensions and usually they are best fixed locally. E.g. figure out which class is getting the rewrite and modify it locally to extend the Cm_OrderProducts class instead of the core one. You may still have other issues, but you'll just have to figure them out. I already made Cm_OrderProducts use as few rewrites as possible (at least as of CE 1.6).
